2023/03/29 10:27:07 httpRequest.go:21: request err:Get "https://api.etherscan.io/api?module=logs&action=getLogs&fromBlock=12878196&toBlock=12879196&address=0xdac17f958d2ee523a2206206994597c13d831ec7&topic0=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef&topic0_2_opr=and&topic2=0x000000000000000000000000dAC17F958D2ee523a2206206994597C13D831ec7&page=1&offset=1000&apikey=YourApiKeyToken": dial tcp 67.230.169.182:443: connectex: No connection could be made because the target machine actively refused it.
2023/03/29 10:28:29 httpRequest.go:22: request err:Get "https://api.etherscan.io/api?module=logs&action=getLogs&fromBlock=12878196&toBlock=12879196&address=0xdac17f958d2ee523a2206206994597c13d831ec7&topic0=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef&topic0_2_opr=and&topic2=0x000000000000000000000000dAC17F958D2ee523a2206206994597C13D831ec7&page=1&offset=1000&apikey=YourApiKeyToken": dial tcp 75.126.135.131:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2023/03/29 10:39:09 httpRequest.go:21: request err:Get "https://api.etherscan.io/api?module=logs&action=getLogs&fromBlock=12878196&toBlock=12879196&address=0xdac17f958d2ee523a2206206994597c13d831ec7&topic0=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef&topic0_2_opr=and&topic2=0x000000000000000000000000dAC17F958D2ee523a2206206994597C13D831ec7&page=1&offset=1000&apikey=H54IJ6ST42QW9GAAFBUZPM7D2P3BRUXR6D": dial tcp [2a03:2880:f12d:83:face:b00c:0:25de]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
